/**
 * process-sprites.ts — Post-processing for AI-generated sprite images.
 *
 * Takes raw grid images from assets/generated/ subdirectories and:
 * 1. Splits grids into individual frame PNGs
 * 2. Resizes frames to target pixel dimensions
 * 3. Validates frame counts match expected animation definitions
 *
 * Usage: npx tsx scripts/process-sprites.ts
 *
 * Expected input structure:
 *   assets/generated/characters/char_0_raw.png  (grid: 8×6 or 16×3, auto-detected)
 *   assets/generated/items/pickups_raw.png       (grid: all pickups in one sheet)
 *   assets/generated/items/projectiles_raw.png   (grid: all projectiles)
 *   assets/generated/vehicles/vehicle_X_raw.png  (grid: 4 directional frames)
 *   assets/generated/environment/tiles_raw.png   (grid: all env tiles)
 *
 * Output: individual frame PNGs in same directories, named by convention:
 *   char_{index}_{state}_{dir}_{frame}.png
 *   pickup_{weaponId}.png
 *   proj_{weaponId}.png
 *   vehicle_{vehicleId}_{dir}.png
 *   env_{name}.png
 */

import { createCanvas, loadImage } from "@napi-rs/canvas";
import * as fs from "fs";
import * as path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const ASSETS_DIR = path.resolve(__dirname, "../public/assets/generated");

// ─── Green screen removal ──────────────────────────────────────────

/**
 * Remove green (#00FF00-ish) pixels from a canvas, making them transparent.
 * Uses a tolerance-based approach to handle anti-aliased edges.
 */
function removeGreenScreen(canvas: ReturnType<typeof createCanvas>): void {
  const ctx = canvas.getContext("2d");
  const imageData = ctx.getImageData(0, 0, canvas.width, canvas.height);
  const data = imageData.data;

  for (let i = 0; i < data.length; i += 4) {
    const r = data[i];
    const g = data[i + 1];
    const b = data[i + 2];

    // Pure green detection: high green, low red and blue
    // Tolerance handles JPEG compression artifacts and anti-aliasing
    if (g > 100 && g > r * 1.4 && g > b * 1.4) {
      // How "green" is this pixel? Scale alpha by how close to pure green
      const greenness = (g - Math.max(r, b)) / g;
      if (greenness > 0.3) {
        // Fully or partially transparent based on greenness
        data[i + 3] = Math.max(0, Math.floor(255 * (1 - greenness)));
        // Despill: remove green tint from semi-transparent edge pixels
        if (data[i + 3] > 0) {
          data[i + 1] = Math.min(g, Math.max(r, b));
        }
      }
    }
  }

  ctx.putImageData(imageData, 0, 0);
}

// ─── Character grid layout ─────────────────────────────────────────
// Supports two grid formats (auto-detected from image dimensions):
//
// FORMAT A (8×6): 8 columns, 6 rows — 2 rows per direction
//   Rows 1-2: facing DOWN,  Rows 3-4: facing UP,  Rows 5-6: facing RIGHT
//   Per direction (across 2 rows of 8):
//     Row A: idle(2), walk(4), melee wind-up, melee swing
//     Row B: melee recovery, ranged aim, ranged fire, death(3), dash(2)
//
// FORMAT B (16×3): 16 columns, 3 rows — 1 row per direction
//   Row 1: DOWN, Row 2: UP, Row 3: RIGHT
//   Per row: idle(2) + walk(4) + melee(3) + ranged(2) + death(3) + dash(2) = 16
//
// Left direction is always auto-generated by flipping right.

interface AnimSlice {
  state: string;
  frames: number;
}

const ANIM_SEQUENCE: AnimSlice[] = [
  { state: "idle", frames: 2 },
  { state: "walk", frames: 4 },
  { state: "attack_melee", frames: 3 },
  { state: "attack_ranged", frames: 2 },
  { state: "death", frames: 3 },
  { state: "dash", frames: 2 },
];

const DIRS_IN_ORDER = ["down", "up", "right"] as const;
const CHAR_TARGET_SIZE = 32; // output frame size
const FRAMES_PER_DIR = ANIM_SEQUENCE.reduce((s, a) => s + a.frames, 0); // 16

// ─── Process characters ─────────────────────────────────────────────

async function processCharacter(charIndex: number): Promise<boolean> {
  const rawPath = path.join(ASSETS_DIR, "characters", `char_${charIndex}_raw.png`);
  if (!fs.existsSync(rawPath)) {
    console.log(`  [skip] char_${charIndex}_raw.png not found`);
    return false;
  }

  console.log(`  Processing character ${charIndex}...`);
  const img = await loadImage(rawPath);

  // Auto-detect grid format from aspect ratio
  const aspectRatio = img.width / img.height;
  let gridCols: number;
  let gridRows: number;
  let rowsPerDir: number;

  if (aspectRatio > 3) {
    // Wide image: 16×3 format (one row per direction)
    gridCols = 16;
    gridRows = 3;
    rowsPerDir = 1;
    console.log(`  Detected 16×3 format (${img.width}×${img.height})`);
  } else {
    // Closer to square: 8×6 format (two rows per direction)
    gridCols = 8;
    gridRows = 6;
    rowsPerDir = 2;
    console.log(`  Detected 8×6 format (${img.width}×${img.height})`);
  }

  const cellW = Math.floor(img.width / gridCols);
  const cellH = Math.floor(img.height / gridRows);
  console.log(`  Cell size: ${cellW}×${cellH}`);

  for (let dirIdx = 0; dirIdx < DIRS_IN_ORDER.length; dirIdx++) {
    const dir = DIRS_IN_ORDER[dirIdx];
    let frameIdx = 0; // sequential frame index within this direction (0-15)

    for (const slice of ANIM_SEQUENCE) {
      for (let f = 0; f < slice.frames; f++) {
        // Calculate source position based on format
        let sx: number, sy: number;
        if (rowsPerDir === 1) {
          // 16×3: all 16 frames in one row
          sx = frameIdx * cellW;
          sy = dirIdx * cellH;
        } else {
          // 8×6: 16 frames split across 2 rows of 8
          const localCol = frameIdx % gridCols;
          const localRow = Math.floor(frameIdx / gridCols);
          sx = localCol * cellW;
          sy = (dirIdx * rowsPerDir + localRow) * cellH;
        }

        const canvas = createCanvas(CHAR_TARGET_SIZE, CHAR_TARGET_SIZE);
        const ctx = canvas.getContext("2d");
        ctx.imageSmoothingEnabled = false;
        ctx.drawImage(img, sx, sy, cellW, cellH, 0, 0, CHAR_TARGET_SIZE, CHAR_TARGET_SIZE);
        removeGreenScreen(canvas);

        // Save down/up/right
        const frameName = `char_${charIndex}_${slice.state}_${dir}_${f}`;
        const outPath = path.join(ASSETS_DIR, "characters", `${frameName}.png`);
        fs.writeFileSync(outPath, canvas.toBuffer("image/png"));

        // Generate left by flipping right
        if (dir === "right") {
          const flipCanvas = createCanvas(CHAR_TARGET_SIZE, CHAR_TARGET_SIZE);
          const flipCtx = flipCanvas.getContext("2d");
          flipCtx.imageSmoothingEnabled = false;
          flipCtx.translate(CHAR_TARGET_SIZE, 0);
          flipCtx.scale(-1, 1);
          flipCtx.drawImage(canvas, 0, 0);

          const leftName = `char_${charIndex}_${slice.state}_left_${f}`;
          const leftPath = path.join(ASSETS_DIR, "characters", `${leftName}.png`);
          fs.writeFileSync(leftPath, flipCanvas.toBuffer("image/png"));
        }

        frameIdx++;
      }
    }
  }

  // Extract preview (first idle-down frame, scaled to 48×48)
  {
    const canvas = createCanvas(48, 48);
    const ctx = canvas.getContext("2d");
    ctx.imageSmoothingEnabled = false;
    ctx.drawImage(img, 0, 0, cellW, cellH, 0, 0, 48, 48);
    removeGreenScreen(canvas);
    const previewPath = path.join(ASSETS_DIR, "characters", `char_preview_${charIndex}.png`);
    fs.writeFileSync(previewPath, canvas.toBuffer("image/png"));
  }

  console.log(`  ✓ Character ${charIndex} split into ${FRAMES_PER_DIR * 4} frames (including left flip)`);
  return true;
}

// ─── Process pickups ────────────────────────────────────────────────

const WEAPON_IDS = [
  "fists", "oboe", "signed_baseball_bat", "ceremonial_sword", "skis",
  "kayak", "rusty_power_drill", "indian_rug", "records", "box_of_antiques",
  "knife_set", "rare_coins", "paint_cans", "microwave", "bb_gun",
];

const CONSUMABLE_IDS = ["health_pack", "speed_boost", "shield", "damage_boost"];

async function processPickups(): Promise<boolean> {
  const rawPath = path.join(ASSETS_DIR, "items", "pickups_raw.png");
  if (!fs.existsSync(rawPath)) {
    console.log("  [skip] pickups_raw.png not found");
    return false;
  }

  console.log("  Processing pickups...");
  const img = await loadImage(rawPath);

  const allIds = [...WEAPON_IDS, ...CONSUMABLE_IDS];
  const cols = Math.ceil(Math.sqrt(allIds.length));
  const cellSize = Math.floor(img.width / cols);
  const targetSize = 16;

  for (let i = 0; i < allIds.length; i++) {
    const col = i % cols;
    const row = Math.floor(i / cols);
    const sx = col * cellSize;
    const sy = row * cellSize;

    const canvas = createCanvas(targetSize, targetSize);
    const ctx = canvas.getContext("2d");
    ctx.imageSmoothingEnabled = false;
    ctx.drawImage(img, sx, sy, cellSize, cellSize, 0, 0, targetSize, targetSize);

    const outPath = path.join(ASSETS_DIR, "items", `pickup_${allIds[i]}.png`);
    fs.writeFileSync(outPath, canvas.toBuffer("image/png"));
  }

  console.log(`  ✓ ${allIds.length} pickups split`);
  return true;
}

// ─── Process projectiles ────────────────────────────────────────────

const RANGED_WEAPON_IDS = [
  "records", "box_of_antiques", "knife_set", "rare_coins",
  "paint_cans", "microwave", "bb_gun",
];

async function processProjectiles(): Promise<boolean> {
  const rawPath = path.join(ASSETS_DIR, "items", "projectiles_raw.png");
  if (!fs.existsSync(rawPath)) {
    console.log("  [skip] projectiles_raw.png not found");
    return false;
  }

  console.log("  Processing projectiles...");
  const img = await loadImage(rawPath);

  const cols = RANGED_WEAPON_IDS.length;
  const cellSize = Math.floor(img.width / cols);
  const targetSize = 8;

  for (let i = 0; i < RANGED_WEAPON_IDS.length; i++) {
    const sx = i * cellSize;

    const canvas = createCanvas(targetSize, targetSize);
    const ctx = canvas.getContext("2d");
    ctx.imageSmoothingEnabled = false;
    ctx.drawImage(img, sx, 0, cellSize, cellSize, 0, 0, targetSize, targetSize);

    const outPath = path.join(ASSETS_DIR, "items", `proj_${RANGED_WEAPON_IDS[i]}.png`);
    fs.writeFileSync(outPath, canvas.toBuffer("image/png"));
  }

  console.log(`  ✓ ${RANGED_WEAPON_IDS.length} projectiles split`);
  return true;
}

// ─── Process vehicles ───────────────────────────────────────────────

const VEHICLE_IDS = ["office_chair", "red_wagon", "golf_cart", "jet_ski", "fork_lift"];
const VEHICLE_DIRS = ["down", "up", "right", "left"] as const;

async function processVehicles(): Promise<boolean> {
  let processed = 0;
  for (const vehicleId of VEHICLE_IDS) {
    const rawPath = path.join(ASSETS_DIR, "vehicles", `vehicle_${vehicleId}_raw.png`);
    if (!fs.existsSync(rawPath)) continue;

    const img = await loadImage(rawPath);
    const cellSize = Math.floor(img.width / 4);
    const targetSize = 40;

    for (let i = 0; i < VEHICLE_DIRS.length; i++) {
      const sx = i * cellSize;

      const canvas = createCanvas(targetSize, targetSize);
      const ctx = canvas.getContext("2d");
      ctx.imageSmoothingEnabled = false;
      ctx.drawImage(img, sx, 0, cellSize, cellSize, 0, 0, targetSize, targetSize);

      const outPath = path.join(ASSETS_DIR, "vehicles", `vehicle_${vehicleId}_${VEHICLE_DIRS[i]}.png`);
      fs.writeFileSync(outPath, canvas.toBuffer("image/png"));
    }
    processed++;
  }

  if (processed > 0) {
    console.log(`  ✓ ${processed} vehicles split`);
  } else {
    console.log("  [skip] No vehicle raw images found");
  }
  return processed > 0;
}

// ─── Process environment tiles ──────────────────────────────────────

const ENV_TILES = [
  "floor", "floor_accent", "wall", "wall_top", "wall_front",
  "locker_closed", "locker_open", "shadow",
];

async function processEnvironment(): Promise<boolean> {
  const rawPath = path.join(ASSETS_DIR, "environment", "tiles_raw.png");
  if (!fs.existsSync(rawPath)) {
    console.log("  [skip] tiles_raw.png not found");
    return false;
  }

  console.log("  Processing environment tiles...");
  const img = await loadImage(rawPath);

  const cols = ENV_TILES.length;
  const cellSize = Math.floor(img.width / cols);
  const targetSize = 32;

  for (let i = 0; i < ENV_TILES.length; i++) {
    const sx = i * cellSize;
    const h = ENV_TILES[i] === "shadow" ? 16 : targetSize;

    const canvas = createCanvas(targetSize, h);
    const ctx = canvas.getContext("2d");
    ctx.imageSmoothingEnabled = false;
    ctx.drawImage(img, sx, 0, cellSize, cellSize, 0, 0, targetSize, h);

    const outPath = path.join(ASSETS_DIR, "environment", `env_${ENV_TILES[i]}.png`);
    fs.writeFileSync(outPath, canvas.toBuffer("image/png"));
  }

  console.log(`  ✓ ${ENV_TILES.length} environment tiles split`);
  return true;
}

// ─── Main ───────────────────────────────────────────────────────────

async function main() {
  console.log("=== Sprite Post-Processing ===\n");
  console.log(`Assets directory: ${ASSETS_DIR}\n`);

  // Characters
  console.log("Characters:");
  let charCount = 0;
  for (let i = 0; i < 9; i++) {
    if (await processCharacter(i)) charCount++;
  }
  console.log(`  ${charCount}/9 characters processed\n`);

  // Items
  console.log("Items:");
  await processPickups();
  await processProjectiles();
  console.log();

  // Vehicles
  console.log("Vehicles:");
  await processVehicles();
  console.log();

  // Environment
  console.log("Environment:");
  await processEnvironment();
  console.log();

  console.log("=== Done ===");
  console.log("Run `npm run pack-atlas` next to build Phaser JSON atlases.");
}

main().catch((err) => {
  console.error("Error:", err);
  process.exit(1);
});
